### ISSUE TITLE
Pleask app is not working 

### ISSUE THREAD

**Issue by jatinrana** [cloudrack-ca/cloudrack-umbrel-apps#42]
I have tried both below method to install plesk app in umbrel, but its not getting started in the umbrel 

just showing starting

![Screenshot (20)](https://github.com/cloudrack-ca/cloudrack-umbrel-apps/assets/4679267/81cd2f0f-e2a9-4b37-8355-c98b547599b0)

1) CMD 
2) Umbrel store

**Comment by cloudrack-ca** [comment]
Thank you for reporting this i will look into the matter at hand if not mistaken from last time I remember you actually need to go to the defined port and setup plesk for this issue to self resolve.

- if this does not address the matter please inform me and I will look into rebuilding/fixing the image in question.
Also like to note the IMPORTANT NOTICE that was already listed about plesk 😒

https://github.com/cloudrack-ca/cloudrack-umbrel-apps?tab=readme-ov-file#plesk-is-not-runnable-currently-and-will-not-uninstall-via-ui---if-you-are-having-these-issues-please-message-me-on-discord

as stated above if you can go to the port listed and set up plesk  (More info found in link below) - 

https://github.com/cloudrack-ca/cloudrack-umbrel-apps/blob/master/cloudrack-plesk/umbrel-app.yml

and nothing still works report back please.

also please make sure ports are not blocked or in use.

- '8540:80'
- '4463:443'
- '8880:8880'
- '8443:8443'
- '8447:8447'
- '3332:21'
- '3844:3306'
